### ISSUE TITLE
I keep getting this error, whether from source

### ISSUE THREAD

**Issue by Em-Lopez** [jremmons/pyfakewebcam#3]
File "build/bdist.linux-x86_64/egg/pyfakewebcam/__init__.py", line 3, in <module>   
File "build/bdist.linux-x86_64/egg/pyfakewebcam/pyfakewebcam.py", line 8, in <module> 
ImportError: No module named v4l2

**Comment by Em-Lopez** [comment]
So I cd'd into the directory and it lets me `import v4l2 as _v4l2 ` without any issues, but `import pyfakewebcam.v4l2 as _v4l2` is like a sin and evil. Why won't this work.

**Comment by Em-Lopez** [comment]
Ok I solved it in pyfakewebcam.py `import pyfakewebcam.v4l2 as _v4l2` -> `from pyfakewebcam import v4l2 as _v4l2`

**Comment by phacribeth** [comment]
Ok, actually that didn't work. I tried it again and it completely failed. I ended up having to navigate to the pyfakeweb cam directory and
import v4l2 as _v4l2
import pyfakewebcam
and then cd out of the directory. I have no idea why this is necessary; it is probably my poor understanding of import and python

**Comment by jremmons** [comment]
I'll try to take a look into the issue you guys are having this weekend. I'll push out updates if necessary!

**Comment by serbuh** [comment]
An import problem still appears:
```
>>> import pyfakewebcam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyfakewebcam/__init__.py", line 3, in <module>
    from pyfakewebcam.pyfakewebcam import FakeWebcam
  File "pyfakewebcam/pyfakewebcam.py", line 8, in <module>
    import pyfakewebcam.v4l2 as _v4l2
ImportError: No module named v4l2
```
Can you offer a quick fix? Got confused with the name masking of the modules _pyfakewebcam_ and _v4l2_

**Comment by charlielito** [comment]
This happens with python2. @serbuh
To solve that, import this at the beginning of the `__init__.py` and `pyfakewebcam.py`:
```
from __future__ import absolute_import
```

**Comment by hoshianaaa** [comment]
I solved copy pyfakewebcam.py and v4l2.py to my program directory.And change `import pyfakewebcam.v4l2 as _v4l2` -> `import v4l2 as _v4l2` in pyfakewebcam.py
